apiVersion: v1
kind: Service
metadata:
  name: currency-converter-service
  labels:
    app: currency-converter
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: currency-converter